create support issue template
k8ssandra/reaper-operator pull request #21
Opened 2020-12-01 18:05 UTC by jsanda

2020-12-10 14:05 UTC, burmanm commented on .github/ISSUE_TEMPLATE/support.md
> +**Did you expect to see some different?**
See some difference or see something different?

2020-12-10 14:06 UTC, burmanm commented on .github/ISSUE_TEMPLATE/support.md
> +Please provide the follow info if you deployed reaper-operator via the
following info?

2021-01-08 05:06 UTC, jdonenine requested changes
Just a couple of small typos.

2021-01-08 15:48 UTC, jdonenine approved these changes
I pushed a commit with the fixes for the minor typos.  Good to go.

2021-01-08 15:49 UTC, merged