Replace schemaJob with a call to management API
k8ssandra/reaper-operator pull request #44
Opened 2021-05-06 17:15 UTC by burmanm

WIP, creates only the Keyspace at this point (management-api has no support for creating the tables themselves yet).

2021-05-10 20:24 UTC, jeffbanks requested changes

2021-05-10 20:24 UTC, jeffbanks commented on pkg/reconcile/reconcilers_test.go
> +/*
Dead code.

2021-05-11 04:29 UTC, burmanm commented on controllers/suite_test.go
> +	// time.Sleep(20 * time.Second)
Dead code.

2021-05-11 04:29 UTC, burmanm commented on pkg/reconcile/reconcilers_test.go
>  	"testing"
No.

2021-05-11 04:31 UTC, burmanm commented on test/config/kind/kind_config_1_worker.yaml
> +kind: Cluster
reaper-operator has had different folder naming (long before k8ssandra test naming)

2021-05-11 04:32 UTC, burmanm commented on test/framework/framework.go
> +	Expect(err).ToNot(HaveOccurred(), fmt.Sprintf("kubectl wait failed: %s", err))
I don't think that matters, we're mostly checking error here for the execution code (whatever kubectl returns). So there should always be output.

2021-05-11 13:56 UTC, jeffbanks commented on test/config/kind/kind_config_1_worker.yaml
> +kind: Cluster
Fair enough.

2021-05-11 14:00 UTC, jeffbanks commented on pkg/reconcile/reconcilers_test.go
>  	"testing"
Not that this code base is too big, but that approach can make it _interesting_ for developers when they see a `test/` folder and then later see `_test.go` files residing along side non-test files.  

Just not the approach we've been following in our other repositories for K8ssandra.  Not a show stopper for me though.

2021-05-11 14:00 UTC, jeffbanks commented on Makefile
> +	test -f ${ENVTEST_ASSETS_DIR}/setup-envtest.sh || curl -sSLo ${ENVTEST_ASSETS_DIR}/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh
Gotcha, didn't know the backstory here, thanks.

2021-05-11 14:58 UTC, jeffbanks approved these changes

2021-05-12 11:49 UTC, merged